name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Pre-Reqs
        run: sudo apt-get install nopt
      - name: Install node-gyp
        run: sudo apt-get install -y node-gyp
      - name: Install modules
        run: yarn
      - name: Compile debug build
        run: |
          node-gyp clean
          node-gyp configure
          node-gyp build --debug
      - name: Run tests
        run: yarn test
